name: Run linters

on:
  push:

permissions:
  checks: write
  contents: read

jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Cache clang-format
        id: clang-cache
        uses: actions/cache@v5
        with:
          path: ~/.cache
          key: clang-format-cache

      - if: ${{ steps.clang-cache.outputs.cache-hit != 'true' }}
        name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
          mkdir -p ~/.cache
          cp /usr/bin/clang-format ~/.cache/clang-format

      - if: ${{ steps.clang-cache.outputs.cache-hit == 'true' }}
        name: Restore clang-format from cache
        run: |
          sudo cp ~/.cache/clang-format /usr/bin/clang-format
          sudo chmod +x /usr/bin/clang-format

      - name: Run clang-format
        run: ./ci/clang-format.sh

  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Cache clang-tidy
        id: clang-cache
        uses: actions/cache@v5
        with:
          path: ~/.cache
          key: clang-tidy-cache

      - if: ${{ steps.clang-cache.outputs.cache-hit != 'true' }}
        name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy
          mkdir -p ~/.cache
          cp /usr/bin/clang-tidy ~/.cache/clang-tidy

      - if: ${{ steps.clang-cache.outputs.cache-hit == 'true' }}
        name: Restore clang-tidy from cache
        run: |
          sudo cp ~/.cache/clang-tidy /usr/bin/clang-tidy
          sudo chmod +x /usr/bin/clang-tidy

      - name: Install build tools
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang cmake ninja-build lld

      - name: Run clang-tidy
        run: ./ci/clang-tidy.sh